### PR TITLE
Max Attendees Feature

### PR DESCRIPTION
**Pull request by Afraz0Khan**

### CODE REVIEW

**Comment by Afraz0Khan** [comment]
Need confirmation on which constructors in the Event class need max_attendees added k thx

**Comment by Mikael-UofA** [comment]
> Need confirmation on which constructors in the Event class need max_attendees added k thx

For both constructors (not including the empty constructor), because the first one is when the organizer is creating the event, and the second one we're going to need it as well because we're retrieving the event from Firestore

**Review by john00003 — CHANGES_REQUESTED** [review]
add maxAttendees to the second constructor (line 52)

**Comment by Afraz0Khan** [comment]
I've made the requested changes. Lmk if it's gtg

**Review by john00003 — APPROVED** [review]
BEAUTIFUL! lgtm

**Pull request merged**
